### PR TITLE
Motion sensors

### PR DESCRIPTION
**Pull request by adrum**
Added the ability to have motion sensors from HomeKit. This works by looking for motion recordings in the past 3 minutes or the minimum email/alert cool down time.

The motion sensors will not be setup if the cameras do not have motion recording enabled.

Push notifications with screenshots from the camera will be sent if the camera and the motion sensor are in the same room in HomeKit.

### CODE REVIEW

**Comment by kieranmjones** [comment]
This is a really addition, I look forward to seeing it merged in and testing it out!

**Comment by gozoinks** [comment]
This looks awesome. Thank you for jumping in! I will spend some time with this. I think I will have some questions.

**Comment by adrum** [comment]
@gozoinks I've not determined what best balance for Motion settings are. Feel free to make suggestions on what time span we should be using for the filtering of motion recordings. For the start time, it currently uses `alertSettings.motionEmailCoolDownMs` or 3 minutes ago--whichever is bigger. It's probably not too much of a worry since the user can configure it from Unifi Video. 

This setting can be found in the Unifi Video settings at Settings -> Minutes Between Motion Alert Emails.

I also made the upper bounds of the motion recordings filter to be two hours in the future, in case there was a time drift with the system running the NVR software. I no longer really need this feature since I stopped using Docker for macOS. I'm now using Linux, which doesn't experience this bug.

**Comment by adrum** [comment]
@gozoinks Have you had a chance to review this yet?

**Comment by jnanes** [comment]
i updated to latest build and see all the motion sensors, they are showing status updates and appear to be working. However, I am not getting notifications with screenshots. I placed all cameras and sensors in a single Homekit room called Cameras, as well as separating them into their individual rooms with no luck. Any ideas on where to troubleshoot? Motion is definitely enabled, and everything else works well in regard to the plugin.

**Comment by jnanes** [comment]
disregard, after some reboots its working!

**Comment by gozoinks** [comment]
What if you move just one sensor and just one cam into a room?

**Comment by gozoinks** [comment]
Disregarding!

**Comment by jnanes** [comment]
Thanks for the reply !! Was excited to see an updatee to a plugin I love.

**Comment by gozoinks** [comment]
Yeah the motion sensor stuff is really fun, and really well done. It’s even more viable with the slightly better accuracy in the UVC beta. Glad it’s working for you!

**Comment by jnanes** [comment]
That’s different than 3.9.7 Uvc?

Thanks,

Jesse Nanes

**Comment by gozoinks** [comment]
Sorry, yes I mean 3.9.7!

**Pull request merged**
