### PR TITLE
Adds random SSRC to cameras instead of the static 1 to allow multiple live streams

### PR DESCRIPTION
**Pull request by adrum**
… live streams

Per the HAP changes, https://github.com/KhaosT/HAP-NodeJS/pull/558

### CODE REVIEW

**Comment by KhaosT** [comment]
Make sure you generate it as `Int32` instead of `UInt32` otherwise ffmpeg will not be happy about that.
```
let ssrcSource = crypto.randomBytes(4);
ssrcSource[0] = 0;
let ssrc = ssrcSource.readInt32BE(0, true);
```

**Comment by dsully** [comment]
+1

**Comment by heccoder** [comment]
+1
This is required to use this plugin with other apps like Homecam.

**Comment by gozoinks** [comment]
Thank you

**Pull request merged**
